//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsecVDisplay.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParsecVDisplay.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 LanguagesResx 的本地化字符串。
        /// </summary>
        internal static string LanguagesResx {
            get {
                return ResourceManager.GetString("LanguagesResx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add display 的本地化字符串。
        /// </summary>
        internal static string t_add_display {
            get {
                return ResourceManager.GetString("t_add_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        internal static string t_apply {
            get {
                return ResourceManager.GetString("t_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for update 的本地化字符串。
        /// </summary>
        internal static string t_check_for_update {
            get {
                return ResourceManager.GetString("t_check_for_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom... 的本地化字符串。
        /// </summary>
        internal static string t_custom {
            get {
                return ResourceManager.GetString("t_custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string t_exit {
            get {
                return ResourceManager.GetString("t_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fallback display 的本地化字符串。
        /// </summary>
        internal static string t_fallback_display {
            get {
                return ResourceManager.GetString("t_fallback_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add a virtual display first! 的本地化字符串。
        /// </summary>
        internal static string t_hint_add_display_first {
            get {
                return ResourceManager.GetString("t_hint_add_display_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep screen on 的本地化字符串。
        /// </summary>
        internal static string t_keep_screen_on {
            get {
                return ResourceManager.GetString("t_keep_screen_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landscape 的本地化字符串。
        /// </summary>
        internal static string t_landscape {
            get {
                return ResourceManager.GetString("t_landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landscape (flipped) 的本地化字符串。
        /// </summary>
        internal static string t_landscape_flipped {
            get {
                return ResourceManager.GetString("t_landscape_flipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string t_language {
            get {
                return ResourceManager.GetString("t_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not apply custom resolutions, access denied! 的本地化字符串。
        /// </summary>
        internal static string t_msg_custom_access_denied {
            get {
                return ResourceManager.GetString("t_msg_custom_access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found invalid value in slot #{0}. 的本地化字符串。
        /// </summary>
        internal static string t_msg_custom_invalid_slot {
            get {
                return ResourceManager.GetString("t_msg_custom_invalid_slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is disabled, please enable it in Device Manager. 的本地化字符串。
        /// </summary>
        internal static string t_msg_driver_is_disabled {
            get {
                return ResourceManager.GetString("t_msg_driver_is_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver status 的本地化字符串。
        /// </summary>
        internal static string t_msg_driver_status {
            get {
                return ResourceManager.GetString("t_msg_driver_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The driver is not OK, please check again. Current status: {0}. 的本地化字符串。
        /// </summary>
        internal static string t_msg_driver_status_not_ok {
            get {
                return ResourceManager.GetString("t_msg_driver_status_not_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not add more virtual displays, you have exceeded the maximum number ({0}). 的本地化字符串。
        /// </summary>
        internal static string t_msg_exceeded_display_limit {
            get {
                return ResourceManager.GetString("t_msg_exceeded_display_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to add virtual display. 的本地化字符串。
        /// </summary>
        internal static string t_msg_failed_to_add_display {
            get {
                return ResourceManager.GetString("t_msg_failed_to_add_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to obtain the device handle, please check the driver installation again. 的本地化字符串。
        /// </summary>
        internal static string t_msg_failed_to_obtain_handle {
            get {
                return ResourceManager.GetString("t_msg_failed_to_obtain_handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to remove virtual display. 的本地化字符串。
        /// </summary>
        internal static string t_msg_failed_to_remove_display {
            get {
                return ResourceManager.GetString("t_msg_failed_to_remove_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must restart your PC to complete the driver setup. 的本地化字符串。
        /// </summary>
        internal static string t_msg_must_restart_pc {
            get {
                return ResourceManager.GetString("t_msg_must_restart_pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please install the driver first. 的本地化字符串。
        /// </summary>
        internal static string t_msg_please_install_driver {
            get {
                return ResourceManager.GetString("t_msg_please_install_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All added virtual displays will be unplugged.\nDo you still want to exit?. 的本地化字符串。
        /// </summary>
        internal static string t_msg_prompt_leave_all {
            get {
                return ResourceManager.GetString("t_msg_prompt_leave_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your app version is up-to-date. 的本地化字符串。
        /// </summary>
        internal static string t_msg_up_to_date {
            get {
                return ResourceManager.GetString("t_msg_up_to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A new version — v{0} is available.\nTo keep your experience optimal, please update it now.&quot; 的本地化字符串。
        /// </summary>
        internal static string t_msg_update_available {
            get {
                return ResourceManager.GetString("t_msg_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string t_options {
            get {
                return ResourceManager.GetString("t_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orientation 的本地化字符串。
        /// </summary>
        internal static string t_orientation {
            get {
                return ResourceManager.GetString("t_orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent GPU 的本地化字符串。
        /// </summary>
        internal static string t_parent_gpu {
            get {
                return ResourceManager.GetString("t_parent_gpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portrait 的本地化字符串。
        /// </summary>
        internal static string t_portrait {
            get {
                return ResourceManager.GetString("t_portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portrait (flipped) 的本地化字符串。
        /// </summary>
        internal static string t_portrait_flipped {
            get {
                return ResourceManager.GetString("t_portrait_flipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh rate 的本地化字符串。
        /// </summary>
        internal static string t_refresh_rate {
            get {
                return ResourceManager.GetString("t_refresh_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string t_remove {
            get {
                return ResourceManager.GetString("t_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove last display 的本地化字符串。
        /// </summary>
        internal static string t_remove_last_display {
            get {
                return ResourceManager.GetString("t_remove_last_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolution 的本地化字符串。
        /// </summary>
        internal static string t_resolution {
            get {
                return ResourceManager.GetString("t_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore displays 的本地化字符串。
        /// </summary>
        internal static string t_restore_displays {
            get {
                return ResourceManager.GetString("t_restore_displays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run on startup 的本地化字符串。
        /// </summary>
        internal static string t_run_on_startup {
            get {
                return ResourceManager.GetString("t_run_on_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Take screenshot 的本地化字符串。
        /// </summary>
        internal static string t_take_screenshot {
            get {
                return ResourceManager.GetString("t_take_screenshot", resourceCulture);
            }
        }
    }
}
